spring:
  application: 
    name: msclientes
    
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lower-case-service-id: true
          
server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    registrer-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  
